name: 游 PRD FTP Deploy

on:
  push:
    branches:
      - master

# Cancelar workflows anteriores cuando se lance uno nuevo
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ftp-deploy:
    name: Hostalia PRD FTP-Deploy
    runs-on: ubuntu-latest
    environment: PRD
    permissions:
      contents: read
      packages: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install lftp and deploy
        run: |
          # Instalar lftp de forma m치s r치pida usando snap (m치s r치pido que apt)
          sudo snap install lftp
          # Deploy via lftp
          lftp -e "set ftp:ssl-allow yes; set ssl:verify-certificate no; open -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} ${{ secrets.FTP_HOST }}; mirror -R -n -vvv --parallel=20 ./ /; quit"